### ISSUE TITLE
App not working right now

### ISSUE THREAD

**Issue by hasundue** [hasundue/denopendabot#2660]
Apparently, the app has been failing in authentication since a couple of weeks ago with the following error:

```
Error: secretOrPrivateKey must be an asymmetric key when using RS256
    at Object.module.exports [as sign] (file:///node_modules/.deno/jsonwebtoken@9.0.2/node_modules/jsonwebtoken/sign.js:130:22)
    at getToken (file:///node_modules/.deno/universal-github-app-jwt@1.1.1/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
    at githubAppJwt (file:///node_modules/.deno/universal-github-app-jwt@1.1.1/node_modules/universal-github-app-jwt/dist-node/index.js:34:23)
    at getAppAuthentication (file:///node_modules/.deno/@octokit+auth-app@6.0.1/node_modules/@octokit/auth-app/dist-node/index.js:53:86)
    at getInstallationAuthentication (file:///node_modules/.deno/@octokit+auth-app@6.0.1/node_modules/@octokit/auth-app/dist-node/index.js:227:35)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async hook (file:///node_modules/.deno/@octokit+auth-app@6.0.1/node_modules/@octokit/auth-app/dist-node/index.js:393:32)
    at async getDeployEnvUrl (file:///src/app/deployments.ts:46:17)
    at async getDeployId (file:///src/app/deployments.ts:65:15)
    at async getThisDeployEnv (file:///src/app/deployments.ts:73:34)
```

I've tried re-creating keys or whatever (see commit logs) but haven't worked out so far.

**Comment by hasundue** [comment]
It suddenly recovered today😂
There's a silent patch on Deno Deploy or something idk.
